name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: rlespinasse/github-slug-action@1.1.0

    - name: Install Dependencies
      run: |
        sudo apt-get install libncurses-dev
    - name: Build
      run: |
        make
        make clean
        rm -rf .git
    - name: Upload Archive
      uses: actions/upload-artifact@v1
      with:
        name: RomWBW-${{env.GITHUB_REF_SLUG}}-${{env.GITHUB_SHA_SHORT}}
        path: .
